### ISSUE TITLE
這是什麼錯誤?

### ISSUE THREAD

**Issue by zelda0079** [icelam/anime1-downloader#17]
我是用最新版本1.5.1的EXE檔
PYTHON是3.10.7版
有安裝PIPENV
直接開啟EXE檔後出ERROR
https://i.imgur.com/XqE52Bp.png

**Comment by icelam** [comment]
我想是我忘了在自動發怖流程中把config.ini加進壓縮檔，手動下載並把它和EXE檔放進同一個資料夾應該就可以用了。

**Comment by zelda0079** [comment]
> 我想是我忘了在自動發怖流程中把config.ini加進壓縮檔，手動下載並把它和EXE檔放進同一個資料夾應該就可以用了。
> 
> https://github.com/icelam/anime1-downloader/blob/develop/config.ini

可用了謝謝
