### ISSUE TITLE
無法搜索後宮露營

### ISSUE THREAD

**Issue by zelda0079** [icelam/anime1-downloader#22]
[13/Nov/2022:10:08:45 +0800]	INFO	已載入 config.ini: {'max_parallel_download': '3', 'video_directory': 'video'}
[13/Nov/2022:10:08:46 +0800]	INFO	開始搜尋與「後宮露營」相關的動畫
[13/Nov/2022:10:08:47 +0800]	WARNING	輸入的關鍵字「後宮露營」找不到任何東西

https://anime1.pw/%E5%BE%8C%E5%AE%AE%E9%9C%B2%E7%87%9F?cat=28
是不是R18的圖標影響?

**Comment by zelda0079** [comment]
我懂了, 原來網址是anime1.pw, 不過在anime1.me還是能搜索得到

**Comment by icelam** [comment]
@zelda0079 感謝你回報錯誤。

本程式暫不支援Anime1.me的站外搜索，因為Anime1.me與Anime1.pw的原始碼並不相同，需時另行處理。而本程式使用Anime1.me提供的搜尋網址的確未能搜到站外動畫。

Anime1.me提供的搜尋網址:
https://anime1.me/?s=%E5%BE%8C%E5%AE%AE%E9%9C%B2%E7%87%9F%EF%BC%81

鑑於下載Anime1.pw只需在播放器上[按右鍵 > "Save video as"](https://user-images.githubusercontent.com/6780420/201513817-de62bc9a-5d21-4514-aba8-d814cd0f8638.png)，所以暫不考慮修改程式。將來若有更多其他資源在其他網域上載，才會考慮擴展站外支援。如果你有需要，可以自行複製及修改本程式。
